remote_theme: "mmistakes/minimal-mistakes@4.19.3"
plugins:
  - jekyll-include-cache

locale: "en-GB"
title: "Edward Xu"
title_separator: "|"
url: "https://edwardx.com"
logo: ""
repository: "edwaarrdd/home"
masthead_title: "Eddy's Site"
author:
  name: "Edward Xu"
  avatar: "/assets/images/me.jpg"
  bio: "Learn, Program, Climb, Travel"
  location: "Melbourne, AUS"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://edwardx.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/edwaarrdd"
include: ["_pages"]
github: [metadata]

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      related: true