remote_theme: "mmistakes/minimal-mistakes@4.19.3"
plugins:
  - jekyll-include-cache

locale: "en-GB"
title: "Edward Xu"
title_separator: "|"
url: ""
logo: ""
masthead_title: "Eddy's Site"
author:
  name: "Edward Xu"
  avatar: "/assets/images/me.jpg"
  bio: "Learning, Programming, Climbing"
  location: "Melb, AUS"
include: ["_pages"]
breadcrumbs: true
  breadcrumb_home_label: "Home"
  breadcrumb_separator: "/"

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true