remote_theme: "mmistakes/minimal-mistakes@4.19.3"
plugins:
  - jekyll-include-cache

locale: "en-GB"
title: "Edward Xu"
title_separator: "|"
url: "https://edwardx.com"
logo: ""
author:
  name: "Edward Xu"
  avatar: "/assets/images/me.jpeg"
  bio: "Programming, Climbing"
  location: "Melb, AUS"